-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR A JOIN (
    SELECT B.AUTHOR_ID ,B.BOOK_ID, CATEGORY ,SUM(S.SALES) * B.PRICE AS TOTAL_SALES
    FROM BOOK B JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID 
    WHERE TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'
    GROUP BY B.AUTHOR_ID ,B.BOOK_ID, B.PRICE, B.CATEGORY
) B ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY A.AUTHOR_ID, AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;


