-- 코드를 입력하세요
SELECT CART_ID
FROM (
SELECT DISTINCT CART_ID, NAME
FROM CART_PRODUCTS
GROUP BY CART_ID,NAME
HAVING NAME = 'Milk' OR NAME = 'Yogurt'
)
GROUP BY CART_ID
HAVING COUNT(CART_ID) = 2
ORDER BY CART_ID;