-- 코드를 입력하세요
SELECT C.CAR_ID,
    C.CAR_TYPE,
    ((DAILY_FEE*30)*(100-DISCOUNT_RATE)/100) AS FEE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P JOIN CAR_RENTAL_COMPANY_CAR C 
    ON P.CAR_TYPE = C.CAR_TYPE
    WHERE P.DURATION_TYPE = '30일 이상' 
          AND P.CAR_TYPE IN ('세단', 'SUV') 
          AND ((DAILY_FEE*30)*(100-DISCOUNT_RATE)/100) BETWEEN 500000 AND 1999999
          AND NOT EXISTS (
              SELECT DISTINCT H.CAR_ID 
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
              WHERE H.CAR_ID = C.CAR_ID AND 
                    NOT (TO_DATE('2022-11-01 00:00:00', 'YYYY-MM-DD HH24-MI-SS') > END_DATE
                    OR TO_DATE('2022-11-30 00:00:00', 'YYYY-MM-DD HH24-MI-SS') < START_DATE)
          )
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;