-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(O.SALES_DATE,'YYYY')) AS YEAR,
       TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) AS MONTH,
       I.GENDER,
       COUNT(DISTINCT I.USER_ID) AS USERS
FROM ONLINE_SALE O JOIN USER_INFO I ON O.USER_ID = I.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY TO_NUMBER(TO_CHAR(O.SALES_DATE,'YYYY')),
         TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')),
         I.GENDER
ORDER BY YEAR, MONTH, GENDER;
