-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT) * P.PRICE AS TOTAL_SALES
FROM FOOD_ORDER O LEFT JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') LIKE '2022-05' AND P.PRODUCT_ID IS NOT NULL
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;