-- 코드를 입력하세요
SELECT T.HISTORY_ID,
       TRUNC((T.DAILY_FEE * T.DURATION_DAYS) * (1 - NVL(D.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM (
    SELECT
        CASE
            WHEN END_DATE - START_DATE + 1 >= 90 THEN '90일 이상'
            WHEN END_DATE - START_DATE + 1 >= 30 THEN '30일 이상'
            WHEN END_DATE - START_DATE + 1 >= 7 THEN '7일 이상'
            ELSE '7일 미만'
        END AS DURATION_TYPE,
    (END_DATE - START_DATE + 1) AS DURATION_DAYS,
    H.HISTORY_ID,
    H.CAR_ID,
    C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
    WHERE H.CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE = '트럭'
)
) T LEFT JOIN (
SELECT *
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE = '트럭'
) D ON T.DURATION_TYPE = D.DURATION_TYPE 
ORDER BY FEE DESC, HISTORY_ID DESC;