-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER FROM FIRST_HALF
    UNION
    SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER FROM JULY
)
GROUP BY FLAVOR
HAVING SUM(TOTAL_ORDER)
ORDER BY SUM(TOTAL_ORDER) DESC
FETCH FIRST 3 ROWS ONLY;
