-- 코드를 입력하세요
SELECT H.HOUR AS HOUR, NVL(C.COUNT,0) AS COUNT 
FROM (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
) H LEFT JOIN (
    SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(TO_CHAR(DATETIME,'HH24')) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
) C ON H.HOUR = C.HOUR
ORDER BY HOUR;
