-- 코드를 입력하세요
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW R JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
WHERE P.MEMBER_NAME = (
    SELECT P.MEMBER_NAME
    FROM REST_REVIEW R JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
    GROUP BY P.MEMBER_NAME
    ORDER BY COUNT(REVIEW_TEXT) DESC
    FETCH FIRST 1 ROWS ONLY
)
ORDER BY R.REVIEW_DATE, REVIEW_TEXT;