-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_DATE('2022-08-01 00:00:00', 'YYYY-MM-DD HH24-MI-SS') <= START_DATE 
          AND TO_DATE('2022-10-31 00:00:00', 'YYYY-MM-DD HH24-MI-SS') >= START_DATE
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) AND (TO_DATE('2022-08-01 00:00:00', 'YYYY-MM-DD HH24-MI-SS') <= START_DATE 
          AND TO_DATE('2022-10-31 00:00:00', 'YYYY-MM-DD HH24-MI-SS') >= START_DATE)
GROUP BY TO_CHAR(START_DATE, 'MM'), CAR_ID
ORDER BY MONTH, CAR_ID DESC;
