-- 코드를 입력하세요
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
WHERE EXISTS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.CAR_ID = C.CAR_ID AND TO_CHAR(H.START_DATE,'YYYY-MM-DD') LIKE '2022-10%'
)
AND CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;