-- 코드를 입력하세요
SELECT B.TITLE AS TITLE,
B.BOARD_ID AS BOARD_ID,
R.REPLY_ID AS REPLY_ID,
R.WRITER_ID AS WRITER_ID,
R.CONTENTS AS CONTENTS,
TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE TO_CHAR(B.CREATED_DATE,'YYYY-MM-DD') LIKE '2022-10%' 

ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;